#!/bin/bash

# SET LOCAL FOLDER FOR DB FILE
if [ -z "$1" ]
  then
   mkdir $(pwd)/data
   SRC="$(pwd)/data"
  else
   SRC=$1
fi

echo "Database local folder: $SRC"

# SET APPLICATION PORT
if [ -z "$2" ]
  then
   PORT=8888
  else
   PORT=$2
fi

echo "Port: $PORT"

# BUILD
docker build . -t nameserver --build-arg db=/external/db.sqlite3

# RUN
docker run -p $PORT:8800 --mount type=bind,source="$SRC",target=/external nameserver