# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180506_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='allowed',
            new_name='allowed_to',
        ),
    ]
