# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-31 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180831_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
