# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-04 12:35
from __future__ import unicode_literals

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180831_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=50)),
                ('expiration', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='institution',
            managers=[
                ('objects', api.models.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='authentication',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, to_field='namespace'),
        ),
        migrations.AddField(
            model_name='authentication',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL, to_field='namespace'),
        ),
        migrations.AlterUniqueTogether(
            name='authentication',
            unique_together=set([('client', 'target')]),
        ),
    ]
