# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-06 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('namespace', models.CharField(max_length=50, unique=True)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=45)),
                ('port', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='locations',
            field=models.ManyToManyField(to='api.Location'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Institution', to_field='namespace'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('name', 'namespace')]),
        ),
    ]
