# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-06 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180506_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='allowed',
            field=models.ManyToManyField(related_name='dataset_institution', to='api.Institution'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='locations',
            field=models.ManyToManyField(related_name='dataset_location', to='api.Location'),
        ),
    ]
