# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-31 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180831_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={},
        ),
        migrations.AlterModelManagers(
            name='institution',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='institution',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='email',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='username',
        ),
    ]
