# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-31 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180831_1453'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='institution',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='institution',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
