# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-04 13:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180904_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='client',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, to_field='namespace'),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 4, 13, 49, 39, 392125, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL, to_field='namespace'),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='token',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='namespace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='namespace'),
        ),
    ]
